## Objetivo

Para la predicción financiera se han usado modelos que han estado presente por mucho tiempo en el mercado (ARIMA, SARIMA, GARCH, etc.). A estos modelos se les conoce como *Pronósticos de Series de Tiempo* (Time Series Forecasting) dado que tratan con historial de datos donde el tiempo les da su estructura. Estos modelos analizan las tendencias, la estacionalidad y el ruido para aprender los patrones inherentes en el tiempo y hacer la mejor estimación.

Sin embargo, podemos transformar los datos históricos de tal forma que funcione como entrenamiento para nuestros modelos de aprendizaje supervizado y esta transformación de la data se le conoce como *Sliding Window*.

En éste Juppyter Notebook presentaré una manera de usar *Sliding Window* para crear la **Tabla Analítica de Datos** que servirá para alimentar a nuestros modelos. Para esto definiré lo siguiente:

* Ventadas de Observación (vobs): El pasado que el modelo puede ver para aprender patrones. En este caso será de 15 días.
* Ventana de Desempeño (vdes): Es el futuro que quieres predecir. Esta será la variable objetivo. En este caso 1 día.
* Step (stride): Es cuánto se desplaza la ventana cada vez. Controla los pasos que genera y define cuánto se superponen las ventanas. En este caso 3 días de desplazamiento.

## Dependencias

In [11]:
import yfinance as yf
import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.model_selection import TimeSeriesSplit


from scipy import stats

import matplotlib.pyplot as plt
import seaborn as sns
import cufflinks as cf
import plotly.express as px


from functools import reduce
from dateutil.relativedelta import relativedelta as rd

import warnings
import os 

warnings.filterwarnings('ignore')
cf.go_offline()
pd.set_option('display.max_columns', 200)
pd.set_option('display.float_format', '{:,.4f}'.format)

## Lectura de Datos

In [12]:
df = pd.read_csv("df.csv")

### Catálogo de Fechas

Crearemos un catálogo de fechas para poder trabajar con más facilidad.

In [13]:
# Definimos las Ventanas de Observación, Ventanas de Desempeño y los pasos que darán

vobs = 15
vdes = 1
step = 3

In [14]:
cat_date = pd.DataFrame(df['Date'].unique(), columns=['Date']).sort_values(['Date'])
cat_date.insert(0,'id', cat_date.index +1)

In [15]:
df = df.merge(
    cat_date,
    on='Date',
    how='left',
)

df.head()

,Date,Close,High,Low,Open,Volume,sma_5,sma_10,sma_20,ema_10,ema_20,dist_sma10,sma_cross,retorno_1,retorno_5,retorno_10,retorno_20,mom_10,mom_20,risk_5,risk_10,risk_20,range,range_roll_14,rsi_14,macd,macd_signal,macd_hist,day,month,roll_max_20,roll_min_20,dist_resistance,dist_support,vol_sma_10,vol_ratio,id
0,2024-03-11,56.3918,56.4386,55.7739,55.9612,14114300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.6646,NaN,NaN,0.0000,0.0000,0.0000,0,3,NaN,NaN,NaN,NaN,NaN,NaN,1
1,2024-03-12,56.6352,56.8692,56.3637,56.4667,12684600,NaN,NaN,NaN,56.3918,56.3918,NaN,NaN,0.0043,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.5055,NaN,NaN,0.0055,0.0030,0.0024,1,3,NaN,NaN,NaN,NaN,NaN,NaN,2
2,2024-03-13,57.2155,57.2998,56.9160,56.9909,13909500,NaN,NaN,NaN,56.5256,56.5195,NaN,NaN,0.0102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.3838,NaN,NaN,0.0250,0.0120,0.0129,2,3,NaN,NaN,NaN,NaN,NaN,NaN,3
3,2024-03-14,57.0882,57.3713,56.9938,57.1637,13996600,NaN,NaN,NaN,56.8030,56.7751,NaN,NaN,-0.0022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.3774,NaN,NaN,0.0286,0.0176,0.0110,3,3,NaN,NaN,NaN,NaN,NaN,NaN,4
4,2024-03-15,56.5031,57.0410,56.2767,56.6352,36849900,NaN,NaN,NaN,56.8969,56.8655,NaN,NaN,-0.0102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.7643,NaN,NaN,0.0067,0.0144,-0.0077,4,3,NaN,NaN,NaN,NaN,NaN,NaN,5

## Matriz de Predictoras (Sliding Windows)

Para crear nuestra Tabla Analítica de Datos que alimentará a los modelos, usaremos *Sliding Windows* y usaremos las siguientes operaciones como *Feature Engineering*:

* Media
* Mediana
* Desviación Estándard
* Mínimo
* Máximo

Pero antes, necesitamos definir la primera ancla y la última amcla que sean *válidas* (i.e. que tengan suficiente data para los pasos que estoy dando).

In [16]:
anclai, anclaf = df['id'].min() + vobs - 1, df['id'].max() - vdes

print(f"La primera ancla es {anclai} y la ancla final será {anclaf}")
print(f"Se tiene {len(list(range(anclai, anclaf+1, step)))} anclas para trabajar")

La primera ancla es 15 y la ancla final será 499
Se tiene 162 anclas para trabajar

In [17]:
# Definimos las funciones que aplicaremos para feature extraction y la unidad muestral

um = ['ancla']

func = ['mean','median','std','min','max']
funcName = [np.mean, np.median, np.std, np.min, np.max]

varc = ['sma_5',
       'sma_10', 'sma_20', 'ema_10', 'ema_20', 'dist_sma10', 'sma_cross',
       'retorno_1', 'retorno_5', 'retorno_10', 'retorno_20', 'mom_10',
       'mom_20', 'risk_5', 'risk_10', 'risk_20', 'range', 'range_roll_14',
       'rsi_14', 'macd', 'macd_signal', 'macd_hist', 'day', 'month',
       'roll_max_20', 'roll_min_20', 'dist_resistance', 'dist_support',
       'vol_sma_10', 'vol_ratio']

In [18]:
ancla = 15
sub = 3
def ingX(df:pd.DataFrame, ancla:int, sub:int)->pd.DataFrame:
    aux = df.loc[(df['id']<=ancla)&(df['id']>=ancla - sub +1)]

    feats = {}

    for c in varc:
        serie = aux[c]
        
        for nombre,funcion in zip(func,funcName):
            
            feats[f'x_{c}_{nombre}_{sub}'] = funcion(serie)
            
    out = pd.DataFrame([feats])
    out.insert(0,'ancla',ancla)
    return out

In [19]:
# Funciones para poder aplicar la fiunción para todas las anclas y todas las sub anclas
# dado que el resultado serán otros dataframes

apilar = lambda x,y: pd.concat([x,y], ignore_index=True)
cruzar = lambda x,y: x.merge(y, on=um, how='outer')

In [20]:
X = reduce(
    cruzar,
    map(
        lambda sub: reduce(
            apilar,
            map(lambda ancla: ingX(df, ancla, sub), range(anclai, anclaf+1, step))
        ),
        range(step, step+vobs, step)
    )
)

## Vector de predicción

Para obtener el vector de predicción, solo pasaremos el valor de $t+1$ como un valor a predecir en el tiempo $t$. Vean el siguiente ejemplo:

In [21]:
def ingY(df:pd.DataFrame, ancla:int)->pd.DataFrame:
    future = df.loc[df['id'] == ancla + vdes, 'Close']
    
    if len(future) == 0:
        return pd.DataFrame()
    
    y_val = future.values[0] / df.loc[df['id']==ancla, 'Close'].values[0] - 1
    
    return pd.DataFrame({
        'ancla': [ancla],
        'y': [y_val]
    })

In [22]:
y = reduce(
    apilar,
    map(lambda ancla: ingY(df, ancla), range(anclai, anclaf+1, step))
)

In [23]:
tad = X.merge(y, on='ancla',how='inner')

In [24]:
tad = tad.dropna().reset_index(drop=True)
tad.head()

,ancla,x_sma_5_mean_3,x_sma_5_median_3,x_sma_5_std_3,x_sma_5_min_3,x_sma_5_max_3,x_sma_10_mean_3,x_sma_10_median_3,x_sma_10_std_3,x_sma_10_min_3,x_sma_10_max_3,x_sma_20_mean_3,x_sma_20_median_3,x_sma_20_std_3,x_sma_20_min_3,x_sma_20_max_3,x_ema_10_mean_3,x_ema_10_median_3,x_ema_10_std_3,x_ema_10_min_3,x_ema_10_max_3,x_ema_20_mean_3,x_ema_20_median_3,x_ema_20_std_3,x_ema_20_min_3,x_ema_20_max_3,x_dist_sma10_mean_3,x_dist_sma10_median_3,x_dist_sma10_std_3,x_dist_sma10_min_3,x_dist_sma10_max_3,x_sma_cross_mean_3,x_sma_cross_median_3,x_sma_cross_std_3,x_sma_cross_min_3,x_sma_cross_max_3,x_retorno_1_mean_3,x_retorno_1_median_3,x_retorno_1_std_3,x_retorno_1_min_3,x_retorno_1_max_3,x_retorno_5_mean_3,x_retorno_5_median_3,x_retorno_5_std_3,x_retorno_5_min_3,x_retorno_5_max_3,x_retorno_10_mean_3,x_retorno_10_median_3,x_retorno_10_std_3,x_retorno_10_min_3,x_retorno_10_max_3,x_retorno_20_mean_3,x_retorno_20_median_3,x_retorno_20_std_3,x_retorno_20_min_3,x_retorno_20_max_3,x_mom_10_mean_3,x_mom_10_median_3,x_mom_10_std_3,x_mom_10_min_3,x_mom_10_max_3,x_mom_20_mean_3,x_mom_20_median_3,x_mom_20_std_3,x_mom_20_min_3,x_mom_20_max_3,x_risk_5_mean_3,x_risk_5_median_3,x_risk_5_std_3,x_risk_5_min_3,x_risk_5_max_3,x_risk_10_mean_3,x_risk_10_median_3,x_risk_10_std_3,x_risk_10_min_3,x_risk_10_max_3,x_risk_20_mean_3,x_risk_20_median_3,x_risk_20_std_3,x_risk_20_min_3,x_risk_20_max_3,x_range_mean_3,x_range_median_3,x_range_std_3,x_range_min_3,x_range_max_3,x_range_roll_14_mean_3,x_range_roll_14_median_3,x_range_roll_14_std_3,x_range_roll_14_min_3,x_range_roll_14_max_3,x_rsi_14_mean_3,x_rsi_14_median_3,x_rsi_14_std_3,x_rsi_14_min_3,x_rsi_14_max_3,x_macd_mean_3,x_macd_median_3,x_macd_std_3,x_macd_min_3,...,x_retorno_20_median_15,x_retorno_20_std_15,x_retorno_20_min_15,x_retorno_20_max_15,x_mom_10_mean_15,x_mom_10_median_15,x_mom_10_std_15,x_mom_10_min_15,x_mom_10_max_15,x_mom_20_mean_15,x_mom_20_median_15,x_mom_20_std_15,x_mom_20_min_15,x_mom_20_max_15,x_risk_5_mean_15,x_risk_5_median_15,x_risk_5_std_15,x_risk_5_min_15,x_risk_5_max_15,x_risk_10_mean_15,x_risk_10_median_15,x_risk_10_std_15,x_risk_10_min_15,x_risk_10_max_15,x_risk_20_mean_15,x_risk_20_median_15,x_risk_20_std_15,x_risk_20_min_15,x_risk_20_max_15,x_range_mean_15,x_range_median_15,x_range_std_15,x_range_min_15,x_range_max_15,x_range_roll_14_mean_15,x_range_roll_14_median_15,x_range_roll_14_std_15,x_range_roll_14_min_15,x_range_roll_14_max_15,x_rsi_14_mean_15,x_rsi_14_median_15,x_rsi_14_std_15,x_rsi_14_min_15,x_rsi_14_max_15,x_macd_mean_15,x_macd_median_15,x_macd_std_15,x_macd_min_15,x_macd_max_15,x_macd_signal_mean_15,x_macd_signal_median_15,x_macd_signal_std_15,x_macd_signal_min_15,x_macd_signal_max_15,x_macd_hist_mean_15,x_macd_hist_median_15,x_macd_hist_std_15,x_macd_hist_min_15,x_macd_hist_max_15,x_day_mean_15,x_day_median_15,x_day_std_15,x_day_min_15,x_day_max_15,x_month_mean_15,x_month_median_15,x_month_std_15,x_month_min_15,x_month_max_15,x_roll_max_20_mean_15,x_roll_max_20_median_15,x_roll_max_20_std_15,x_roll_max_20_min_15,x_roll_max_20_max_15,x_roll_min_20_mean_15,x_roll_min_20_median_15,x_roll_min_20_std_15,x_roll_min_20_min_15,x_roll_min_20_max_15,x_dist_resistance_mean_15,x_dist_resistance_median_15,x_dist_resistance_std_15,x_dist_resistance_min_15,x_dist_resistance_max_15,x_dist_support_mean_15,x_dist_support_median_15,x_dist_support_std_15,x_dist_support_min_15,x_dist_support_max_15,x_vol_sma_10_mean_15,x_vol_sma_10_median_15,x_vol_sma_10_std_15,x_vol_sma_10_min_15,x_vol_sma_10_max_15,x_vol_ratio_mean_15,x_vol_ratio_median_15,x_vol_ratio_std_15,x_vol_ratio_min_15,x_vol_ratio_max_15,y
0,57,58.8181,58.8470,0.1524,58.6187,58.9886,59.1726,59.1613,0.1220,59.0292,59.3273,59.0896,59.0872,0.0058,59.0839,59.0976,58.9363,58.9350,0.1076,58.8051,59.0687,58.7885,58.7905,0.0420,58.7361,58.8388,-0.0140,-0.0159,0.0033,-0.0167,-0.0094,-0.2714,-0.2401,0.1471,-0.4652,-0.1090,-0.0002,-0.0019,0.0032,-0.0029,0.0044,-0.0159,-0.0163,0.0030,-0.0192,-0.0120,-0.0227,-0.0222,0.0038,-0.0277,-0.0184,-0.0013,-0.0011,0.0017,-0.0035,0.0006,-0.0227,-0.0222,0.0038,-0.0277,-0.0184,-0.0013,-0.0011,0.0017,-0.0035,0.0006,0.0077,0.0078,0.0004,0.0072,0.0082,0.0169,0.0176,0.0012,0.0152,0.0178,0.0282,0.0283,0.0015,0.0264,0.0300,0.6354,0.6888,0.1326,0.4529,0.7643,0.5293,0.5257,0.0135,0.5149,0.5473,38.1268,39.0363,2.0452,35.2943,40.0498,0.2435,0.2319,0.0520,0.1864,...,0.0374,0.0350,-0.0035,0.0936,0.0036,0.0046,0.0183,-0.0277,0.0248,0.0421,0.0374,0.0350,-0.0035,0.0936,0.0068,0.0072,0.0020,0.0025,0.0099,0.0127,0.0135,0.0047,0.0054,0.0185,0.0307,0.0300,0.0039,0.0255,0.0368,0.5410,0.5095,0.1682,0.3397,0.9059,0.6326,0.6390,0.1091,0.5075,0.8479,64.4730,64.5533,18.7624,35.2943,92.2414,0.5758,0.6473,0.1965,0.1864,0.7750,0.5950,0.6162,0.0824,0.4076,0.6861,-0.0192,-0.0310,0.1440,-0.2310,0.1696,2.2000,2.0000,1.3266,0,4,5.0000,5.0000,0.0000,5,5,60.0423,60.1643,0.2343,59.4189,60.1643,56.1553,56.3522,1.2760,54.6631,57.7581,-0.0147,-0.0119,0.0115,-0.0323,0.0035,0.0542,0.0528,0.0332,0.0080,0.0975,"10,453,668.0000","10,136,260.0000","758,100.1692","9,829,760.0000","12,181,840.0000",0.9625,0.9786,0.1529,0.7023,1.2218,0.0155
1,60,58.5885,58.5828,0.1364,58.4243,58.7583,58.8920,58.8829,0.0199,58.8735,58.9197,59.1273,59.1301,0.0328,59.0858,59.1660,58.8538,58.8608,0.0860,58.7451,58.9554,58.7731,58.7751,0.0498,58.7111,58.8330,0.0137,0.0085,0.0079,0.0078,0.0248,-0.5388,-0.5473,0.1038,-0.6615,-0.4076,0.0105,0.0155,0.0074,0.0000,0.0160,0.0209,0.0150,0.0095,0.0135,0.0343,0.0047,-0.0016,0.0123,-0.0062,0.0219,0.0176,0.0152,0.0057,0.0122,0.0255,0.0047,-0.0016,0.0123,-0.0062,0.0219,0.0176,0.0152,0.0057,0.0122,0.0255,0.0111,0.0134,0.0058,0.0030,0.0167,0.0142,0.0139,0.0020,0.0119,0.0168,0.0323,0.0323,0.0006,0.0316,0.0330,0.9468,0.9719,0.2702,0.6039,1.2644,0.5918,0.6046,0.0282,0.5527,0.6181,49.2146,46.5116,6.7556,42.6303,58.5020,0.2665,0.2441,0.0496,0.2202,...,0.0236,0.0292,-0.0035,0.0868,0.0000,0.0024,0.0167,-0.0277,0.0219,0.0294,0.0236,0.0292,-0.0035,0.0868,0.0080,0.0082,0.0035,0.0025,0.0167,0.0120,0.0124,0.0042,0.0054,0.0178,0.0303,0.0300,0.0036,0.0255,0.0368,0.6417,0.6039,0.2507,0.3397,1.2644,0.5916,0.5844,0.0709,0.5075,0.7529,55.9408,58.5020,13.5915,35.2943,75.6492,0.4829,0.4866,0.2110,0.1864,0.7670,0.5529,0.6162,0.1279,0.3430,0.6861,-0.0700,-0.0656,0.1129,-0.2310,0.1292,2.0667,2.0000,1.3400,0,4,5.1333,5.0000,0.3399,5,6,60.1555,60.1643,0.0330,60.0322,60.1643,56.7478,57.6260,1.1245,54.6631,57.7581,-0.0165,-0.0130,0.0099,-0.0323,0.0028,0.0430,0.0470,0.0277,0.0080,0.0892,"10,276,152.6667","10,136,260.0000","421,851.3911","9,829,760.0000","11,125,210.0000",1.0556,1.0102,0.2302,0.7548,1.7812,-0.0003
2,63,59.5749,59.5774,0.3390,59.1584,59.9888,59.1024,59.0980,0.0833,59.0027,59.2066,59.3023,59.3023,0.0501,59.2410,59.3637,59.4087,59.4078,0.1658,59.2061,59.6122,59.1070,59.1041,0.1078,58.9763,59.2404,0.0217,0.0222,0.0024,0.0186,0.0243,0.2725,0.2751,0.2889,-0.0826,0.6251,-0.0002,-0.0003,0.0030,-0.0037,0.0036,0.0289,0.0352,0.0094,0.0156,0.0360,0.0212,0.0183,0.0058,0.0161,0.0293,0.0193,0.0207,0.0020,0.0164,0.0208,0.0212,0.0183,0.0058,0.0161,0.0293,0.0193,0.0207,0.0020,0.0164,0.0208,0.0185,0.0211,0.0050,0.0115,0.0228,0.0166,0.0166,0.0013,0.0151,0.0182,0.0331,0.0331,0.0002,0.0329,0.0333,0.5190,0.4907,0.1211,0.3869,0.6794,0.6345,0.6356,0.0091,0.6228,0.6450,58.4351,58.3501,0.3848,58.0122,58.9431,0.4535,0.4659,0.0384,0.4015,...,0.0164,0.0144,-0.0035,0.0475,0.0001,0.0024,0.0170,-0.0277,0.0293,0.0172,0.0164,0.0144,-0.0035,0.0475,0.0108,0.0084,0.0053,0.0030,0.0228,0.0127,0.0139,0.0045,0.0054,0.0182,0.0298,0.0300,0.0029,0.0255,0.0333,0.6190,0.5190,0.2421,0.3397,1.2644,0.5792,0.5844,0.0515,0.5075,0.6450,52.6207,58.0122,10.0974,35.2943,66.1238,0.4223,0.4015,0.1622,0.1864,0.7158,0.4965,0.4629,0.1308,0.3430,0.6861,-0.0743,-0.0656,0.1066,-0.2310,0.0930,2.2667,2.0000,1.3888,0,4,5.3333,5.0000,0.4714,5,6,60.2348,60.1643,0.1572,60.1643,60.7305,57.2914,57.6260,0.6594,55.6728,57.7581,-0.0153,-0.0130,0.0112,-0.0323,0.0028,0.0354,0.0465,0.0187,0.0080,0.0683,"10,435,286.6667","10,166,350.0000","500,288.4849","9,829,760.0000","11,125,210.0000",1.0225,0.9665,0.2471,0.7548,1.7812,-0.0050
3,66,60.2323,60.2247,0.0511,60.1738,60.2983,59.5327,59.5283,0.1279,59.3783,59.6916,59.4222,59.4264,0.0070,59.4123,59.4278,59.7814,59.7866,0.0332,59.7383,59.8193,59.4020,59.4052,0.0477,59.3421,59.4587,0.0040,0.0074,0.0072,-0.0060,0.0105,0.8101,0.7983,0.0453,0.7615,0.8705,-0.0054,-0.0050,0.0041,-0.0105,-0.0006,-0.0040,-0.0061,0.0110,-0.0163,0.0105,0.0243,0.0256,0.0037,0.0191,0.0280,0.0004,-0.0005,0.0036,-0.0035,0.0052,0.0243,0.0256,0.0037,0.0191,0.0280,0.0004,-0.0005,0.0036,-0.0035,0.0052,0.0136,0.0123,0.0030,0.0109,0.0178,0.0206,0.0210,0.0008,0.0195,0.0213,0.0302,0.0306,0.0021,0.0274,0.0324,0.6920,0.5850,0.1786,0.5473,0.9436,0.6383,0.6390,0.0031,0.6342,0.6417,55.5421,57.1428,4.9705,48.8141,60.6695,0.4526,0.4700,0.0357,0.4028,...,0.0057,0.0099,-0.0035,0.0255,0.0035,0.0024,0.0196,-0.0277,0.0293,0.0094,0.0057,0.0099,-0.0035,0.0255,0.0119,0.0109,0.0054,0.0030,0.0228,0.0156,0.0166,0.0039,0.0077,0.0213,0.0299,0.0306,0.0029,0.0255,0.0333,0.6618,0.6039,0.2444,0.3397,1.2644,0.5823,0.6046,0.0530,0.5075,0.6450,50.8866,49.0477,8.8447,35.2943,64.5533,0.3811,0.4015,0.1164,0.1864,0.5830,0.4457,0.4171,0.0955,0.3430,0.6486,-0.0646,-0.0656,0.1133,-0.2310,0.0930,2.1333,2.0000,1.3098,0,4,5.5333,6.0000,0.4989,5,6,60.3480,60.1643,0.2451,60.1643,60.7305,57.5839,57.6260,0.3044,56.4654,57.7581,-0.0156,-0.0130,0.0113,-0.0323,0.0028,0.0317,0.0305,0.0155,0.0080,0.0528,"10,715,661.3333","10,981,310.0000","614,733.3850","9,829,760.0000","11,822,320.0000",1.0030,0.8772,0.2693,0.7347,1.7812,0.0017
4,69,59.8275,59.8095,0.1573,59.6445,60.0284,59.8704,59.8992,0.0479,59.8029,59.9091,59.4072,59.4094,0.0083,59.3960,59.4160,59.6835,59.6777,0.0366,59.6419,59.7310,59.4473,59.4468,0.0014,59.4460,59.4493,-0.0064,-0.0061,0.0004,-0.0070,-0.0060,0.4203,0.4001,0.1493,0.2485,0.6124,0.0012,0.0011,0.0004,0.0007,0.0017,-0.0131,-0.0137,0.0043,-0.0181,-0.0076,0.0070,0.0028,0.0067,0.0017,0.0165,-0.0018,-0.0022,0.0023,-0.0045,0.0012,0.0070,0.0028,0.0067,0.0017,0.0165,-0.0018,-0.0022,0.0023,-0.0045,0.0012,0.0156,0.0153,0.0034,0.0117,0.0199,0.0128,0.0118,0.0025,0.0103,0.0162,0.0198,0.0201,0.0036,0.0152,0.0239,0.6040,0.5706,0.0573,0.5567,0.6847,0.6775,0.6790,0.0067,0.6686,0.6848,62.8344,62.2807,2.1168,60.5634,65.6591,0.3181,0.3147,0.0278,0.2858,...,0.0012,0.0101,-0.0045,0.0255,0.0069,0.0161,0.0182,-0.0277,0.0293,0.0068,0.0012,0.0101,-0.0045,0.0255,0.0133,0.0123,0.0054,0.0030,0.0228,0.0162,0.0166,0.0031,0.0103,0.0213,0.0287,0.0306,0.0052,0.0152,0.0333,0.6794,0.6039,0.2216,0.3869,1.2644,0.6143,0.6342,0.0526,0.5149,0.6848,52.8306,58.0122,9.4580,35.2943,65.6591,0.3468,0.3353,0.0992,0.1864,0.4932,0.4011,0.4002,0.0455,0.3430,0.5206,-0.0543,-0.0552,0.1081,-0.2310,0.0930,2.0000,2.0000,1.4142,0,4,5.7333,6.0000,0.4422,5,6,60.4612,60.4568,0.2641,60.1643,60.7305,57.6436,57.6260,0.0449,57.6260,57.7581,-0.0153,-0.0130,0.0107,-0.0323,0.0028,0.0328,0.0322,0.0129,0.0080,0.0504,"10,838,120.0000","10,997,680.0000","534,680.0155","10,057,770.0000","11,822,320.0000",1.0118,0.8772,0.2649,0.7347,1.7812,0.0002

## Partición

La partición se hará **Off Time**, es decir, sacamos el 10% del nuestros datos que no verá el modelo. Para los demás conjuntos se utiliza el quantile 0.85 para dividir en train y test.

In [25]:
cut_off = int(tad['ancla'].quantile(0.90))

Sn = tad[tad['ancla'] < cut_off].reset_index(drop=True)
ot = tad[tad['ancla'] >= cut_off].reset_index(drop=True)

cut_ancla = int(Sn['ancla'].quantile(0.85))

train_df = Sn[Sn['ancla'] < cut_ancla].reset_index(drop=True)
test_df  = Sn[Sn['ancla'] >= cut_ancla].reset_index(drop=True)

## EDA

In [26]:
# Revisamos los missings

miss = train_df.isna().sum().reset_index(name='miss').sort_values('miss', ascending=False).reset_index(drop=True)
miss['miss'] = miss['miss'] / len(Sn)
miss

                     index   miss
0                    ancla 0.0000
1           x_sma_5_mean_3 0.0000
2         x_sma_5_median_3 0.0000
3            x_sma_5_std_3 0.0000
4            x_sma_5_min_3 0.0000
..                     ...    ...
747  x_vol_ratio_median_15 0.0000
748     x_vol_ratio_std_15 0.0000
749     x_vol_ratio_min_15 0.0000
750     x_vol_ratio_max_15 0.0000
751                      y 0.0000

[752 rows x 2 columns]

In [27]:
train_df.replace([np.inf, -np.inf], np.nan, inplace=True)
test_df.replace([np.inf, -np.inf], np.nan, inplace=True)

In [28]:
# Revisamos infs
np.isinf(train_df).sum().reset_index(name='infs').sort_values('infs', ascending=False).reset_index(drop=True)

                     index  infs
0                    ancla     0
1           x_sma_5_mean_3     0
2         x_sma_5_median_3     0
3            x_sma_5_std_3     0
4            x_sma_5_min_3     0
..                     ...   ...
747  x_vol_ratio_median_15     0
748     x_vol_ratio_std_15     0
749     x_vol_ratio_min_15     0
750     x_vol_ratio_max_15     0
751                      y     0

[752 rows x 2 columns]

In [29]:
tgt = ['y']

In [30]:
varc = [c for c in train_df.columns if c.startswith('x_')]

imputer = SimpleImputer(strategy='median')

X_train_imp = pd.DataFrame(
    imputer.fit_transform(train_df[varc]),
    columns=varc,
    index=train_df.index
)

X_test_imp = pd.DataFrame(
    imputer.transform(test_df[varc]),
    columns=varc,
    index=test_df.index
)